### ISSUE TITLE
[ENHANCEMENT] - Simplify Pointer Initialization Syntax

### ISSUE THREAD

**Issue by bismapervaiz** [apimatic/go-core-runtime#40]
### Issue Overview
Currently, the initialization of pointer types is verbose and lacks a concise syntax. This verbosity can lead to code clutter and reduce code readability. As the go-core-runtime evolves, it becomes essential to streamline pointer initialization to improve developer experience and make the codebase more maintainable.

### Proposed Solution
To address this issue, we propose enhancing the pointer usage by introducing a more concise and straightforward syntax for pointer initialization.

### Current Verbose Syntax
The current verbose syntax for initializing a pointer to a variable `x` is as follows:
```go
x := 123
var y *int = &x
```

### Proposed Concise Syntax
We suggest introducing a shorthand method for pointer initialization that allows developers to initialize a pointer and set its value in a single line:
```go
x := ToPointer(42)
```

### Benefits
By adopting this concise syntax, the package users will enjoy the following benefits:
1. Improved code readability: The new syntax makes it clear that we are working with a pointer and initializing its value in one step, reducing the need for additional lines of code.
2. Reduced potential for errors: Developers no longer have to manage separate lines for pointer creation and value assignment, reducing the chances of mismatched types or incorrect assignments.
3. Easier to maintain: With a cleaner and more standardized syntax, the codebase becomes easier to maintain, review, and update.

### Additional Considerations
It's essential to ensure that the proposed concise syntax aligns with the package's overall design and coding conventions. We'll need to carefully review and test the implementation to verify its correctness and performance impact.

**Comment by haseeb-mhr** [comment]
### Discussion Overview
@thehappybug As i have discussed on slack that I have these options:

```go
1. ToPointer()
2. Pointer()
3. ToReference()
4. ToIndicator()
5. ToIndex()
```
And your suggestion is to use the `ToPointer()` function signature.

### Current Discussion
Now i want to discuss about where we have to place this `ToPointer()` function implementation. I have the discussion with @bismapervaiz on this and first she suggested to add it in the utilities package but I have three key points:

1. `ToPointer()` function is generated to improve the implementation of Optional Nullable Fields and it is only used when we are generating example code for Optional Nullable Fields.
2. Second its is not a utility function because we can not convert a custom model i.e. `Person` to its public interface i.e. `PersonInterface` Object.
3. Lastly if we add this function to utilities package then we have to handle an other import for this function in our Sdk Code Samples.

I have these key points on its contaning package. I want to hear your suggestion on it. Please response ASAP because i will finalize my implementation after hearing your thoughts.

**Comment by haseeb-mhr** [comment]
Closing because handling was done in Golang SDK.
